language: python
dist: xenial
matrix:
  include:
  - python: "2.7"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
install:
  - pip install -e .
script:
  - python pyml/BoundingBox.py
  - python pyml/Patience.py
  - python pyml/RunningMean.py
  - python pyml/RunningVariance.py
